### ISSUE TITLE
주문하기 상세페이지 기능 구현

### ISSUE THREAD

**Issue by deehyeon** [SOPT-32-CDS/BaeMin-AOS#10]
## ❗ 이슈 요약

- 프로젝트 초기 세팅

## 🔍 체크 리스트

- [x] toolbar 버튼 클릭 시 화면 이동
- [x] 수량 +,- 버튼 클릭 시 수량 변경
- [x] 수량 +,- 버튼 클릭 시 장바구니 추가 금액 변경
- [x] 옵션 추가 버튼 클릭 시 장바구니 추가 금액 변경
- [x] 장바구니 담기 버튼 클릭 시 장바구니 페이지로 이동

**Comment by haeti-dev** [comment]
프로젝트 초기 세팅 하시게요? ㅋㅋㅋㅋ
