### ISSUE TITLE
주문하기 상세 페이지 뷰 만들기

### ISSUE THREAD

**Issue by deehyeon** [SOPT-32-CDS/BaeMin-AOS#5]
## ❗ 이슈 요약

주문하기 상세 페이지 뷰 만들기

## 🔍 체크 리스트

- [x] 툴바 만들기
- [x] 메뉴 이미지/이름/상세/가격 뷰 만들기
- [x] 사이드/추가옵션 메뉴 리사이클러뷰 아이템 만들기
- [x] 중첩(이중) 리사이클러뷰 만들기

**Comment by haeti-dev** [comment]
굳굳
